version: '3.8'

services:
  example-backend:
    image: example-backend
    build: ./example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: example-backend
  example-frontend:
    image: example-frontend
    build: ./example-frontend
    container_name: example-frontend
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db-example-backend
  reverse-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
